language: ruby
rvm:
  - 2.3.1
jdk:
  - oraclejdk8
  - openjdk8
before_script:
  - wget http://nlp.stanford.edu/software/stanford-corenlp-full-2014-10-31.zip
  - unzip stanford-corenlp-full-2014-10-31.zip
  - mv stanford-corenlp-full-2014-10-31/* spec/bin/
  - rm -r stanford-corenlp-full-2014-10-31
  - cp bin/bridge.jar spec/bin
script:
  - rake spec['english']
notifications:
  email: true
